{{- if .Values.configFiles.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dpg-match-score.configFilesName" . }}
  labels:
    {{- include "dpg-match-score.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.configFiles.authKeysFileName }}: |
{{ .Values.configFiles.authKeysJson | indent 4 }}
  {{ .Values.configFiles.aiProvidersFileName }}: |
{{ .Values.configFiles.aiProvidersJson | indent 4 }}
{{- end }}
