{{- if .Values.internalSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dpg-notification-service.internalSecretsName" . }}
  labels:
    {{- include "dpg-notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.internalSecrets.fileName }}: |
{{ .Values.internalSecrets.json | indent 4 }}
{{- end }}
